FROM quay.io/centos/centos:stream8 as builder
WORKDIR /build
COPY rust .
RUN dnf -y install --setopt=install_weak_deps=False \
       binutils git make rust-toolset rpm-build python3 python3-devel && \
    dnf clean all && cargo build --release && strip target/release/*

FROM quay.io/centos/centos:stream8
COPY --from=builder /build/target/release/nmstatectl /usr/bin/nmstatectl
